apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
  namespace: notes-app
  labels:
    app: notes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes
  template:
    metadata:
      labels:
        app: notes
    spec:
      containers:
      - name: notes
        image: priyankaceq/notes-making-app:my_app
        ports:
        - containerPort: 8000