name: Docker--Image-Notes-App 

on:
  workflow_dispatch:    
  push:
    branches: 
      [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository under GitHub Workspace
      uses: actions/checkout@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker Image from Dockerfile
      run: docker build -t priyankaceq/notes-making-app:my_app .

    - name: Show Images in my Docker Registry
      run: docker images 

    - name: Run Docker Image in Detached Mode and Map Random Port to Default Port 
      run: docker run -d -p8001:8000 priyankaceq/notes-making-app:my_app
    
    - name: List only Running Conatiners
      run: docker ps
    
    - name: List all Containers
      run: docker ps -a

    - name: Push Image to the Docker Registry
      run: docker push priyankaceq/notes-making-app:my_app

    - name: Logout from Docker Registry
      run: docker logout